[Feat/#3] 2주차 필수 과제
AND-SOPT-ANDROID/hwiwon-jo pull request #4
Opened 2024-10-24 16:54 UTC by hwidung

## Related issue 🛠
- closed #3

## Work Description ✏️
- 기존 text view 를 Custom Component로 만들어 리팩토링
- MVVM 구조 적용
- Single Activity Architecture 구조 적용
- Bottom Navigation 구현
- LazyLists를 활용한 홈 뷰 구현

## Screenshot 📸
https://github.com/user-attachments/assets/1fc157e2-7329-4952-90f0-40519959802c

## Uncompleted Tasks 😅

## To Reviewers 📢
MVVM 구조로 바꾸는 과정에서 많은 시간이 소요 됐습니다 😅 이 부분에 대해 많은 이야기 나눌 수 있었으면 좋겠습니다 !
시험 기간 이슈로 ,,, 다음에는 더 더 디테일한 부분까지 구현해 보겠습니다 😭

2024-10-24 17:28 UTC, Marchbreeze reviewed
너무 잘하시네요~~~~ 원래 2주차떄부터 MVVM을 적용하나요?!

정답은 없지만, 저는 일반적으로 기능별로 폴더링해서 UI파일과 뷰모델 파일을 함께 두는 편입니다! 이 방법이 규모가 커졌을 때에도 찾고 작업하기 편하더라구요 ㅎㅎ 또한 만약 나중에 feature별 멀티 모듈 구조로 전환하게 된다면 그 과정이 편해질 수 있다는 장점이 있어요

많이 알아보고 생각해보는 경험 추천드립니다 ㅎㅎ 다른 레포 많이 참고해보세요!

2024-10-24 17:28 UTC, Marchbreeze commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +                        )
이 부분은 무의미한 기능을 하고 있는 것처럼 보이는데 확인 가능할까요?
상단에 onValueChange = { signInViewModel.passwordLogin = it }, 부분에서 이미 값 수정을 진행하신 것 같아요!
현재 이함수는 signUpViewModel.emailLogin = signUpViewModel.emailLogin 을 해주는 것처럼 보여요
제가 컴포즈를 몰라서 아닐수도..ㅎㅎ

또한 지금 뷰는 로그인뷰로 보이는데, 로그인의 validate는 버튼 클릭 시에만 진행되어야 할 것 같습니다!
현재처럼 로그인 정보가 타이핑될 때 계속해서 값 변경을 관찰하고 있으면 불필요한 메모리가 될 것 같아요

2024-10-24 17:28 UTC, Marchbreeze commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +                        ) {
이형식은 지금
뷰에서 뷰모델 함수 요청 -> 뷰모델에서 변수값 전달 -> 뷰에서 변수값 그대로 다시 뷰모델에 함수와 함께 전달
처럼 불필요한 변수의 이동을 하고 있는 것처럼 보여요!
signInViewModel.validateSignIn() 으로 두고, 파라미터는 뷰모델 내부에서 처리해보는건 어떨까요?

2024-10-24 17:28 UTC, Marchbreeze commented on app/src/main/java/org/sopt/and/presentation/viewmodel/SignInViewModel.kt
> +
이 경우 자기 자신을 파라미터로 넣게되면 의존성 참조 순환이 발생하지 않나요,,?
제가 뷰모델팩토리를 만들어본지 오래돼서 .. 확인 부탁드립니다!

2024-10-24 17:28 UTC, Marchbreeze commented on app/src/main/java/org/sopt/and/presentation/viewmodel/SignInViewModel.kt
> +    }
지금 두 뷰모델 변수는 private 상태가 아니라 외부에서도 변환 가능해보이는데, 이렇게 설계된 이유가 있을까요?
뷰모델 변수는 private으로 설정해두는 것이 캡슐화를 위해 권장되긴 합니다! 백패킹에 대해서도 한번 알아보면 좋을 것 같아요

2024-10-24 17:28 UTC, Marchbreeze commented on app/src/main/java/org/sopt/and/presentation/viewmodel/SignInViewModel.kt
> +    }
```suggestion
    fun validateSignIn(email: String, password: String) = 
        email == signUpViewModel.email && password == signUpViewModel.password
```
처럼도 표현가능합니다! 더 간결하게 코틀린스럽게 표현하는 함수인데요, 이렇게 쓸수도 있다~ 정도로 알아두시면 좋을 것 같아요 ㅎㅎ

2024-10-24 17:28 UTC, Marchbreeze commented on app/src/main/java/org/sopt/and/presentation/viewmodel/SignUpViewModel.kt
> +        val hasSpecialChar = RegexConstants.SPECIAL_REGEX.containsMatchIn(password)
정규식의 경우 메모리 효율을 최적화해줄 수 있는 방법이 있는데, companion object와 regex에 대해 알아보면 좋을 것 같아요

2024-10-27 13:27 UTC, jangsjw reviewed
파일 분리 등 여러 부분 배우고 가요!! 수고하셨습니다 :)

2024-10-27 13:27 UTC, jangsjw commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> -                        unfocusedContainerColor = Color.Gray
Color.Gray와 같은 하드코딩된 색상 대신 MaterialTheme.colorScheme를 사용하여 일관된 색상을 유지할 수 있을 듯합니다!

2024-10-27 13:27 UTC, jangsjw commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
Header, EmailField, PasswordField, SignInButton 등을 별도의 컴포저블로 분리하면 코드 복잡성을 줄이고 재사용성을 높일 수 있을 것 같습니다!!

2024-10-27 13:27 UTC, jangsjw commented on app/src/main/java/org/sopt/and/presentation/ui/main/HomeScreen.kt
> +        R.drawable.film_poster_dummy
동일한 리소스 반복적으로 정의하고 있는데, List(n) { } 구문을 사용하면 동일한 값을 단일 값으로 줄여 테스트 데이터를 간결하게 작성할 수 있으니 꿀팁 인 것 같아요!

2024-10-27 14:40 UTC, SYAAINN requested changes
MVVM 구조의 탄생과 활용, 백킹 프로퍼티는 무엇인지에 대해 더 학습해보고 어떻게 하면 데이터를 더 안전하고 효과적으로 활용할 수 있을지 고민해봅시다!

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/data/repository/UserRepository.kt
[3]
이 친구는 어쩌다 등장했죠..?!

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/navigation/AuthNavItem.kt
> +}
[3]
sealed class와 object를 사용한 이유는 뭘까요?

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/navigation/AuthNavItem.kt
> +}
[3]
MainScreen의 경우도 AuthNavItem으로 다 묶여있네요! 나중에 설정 등 회원가입이 완료된 유저가 사용할 화면이 더 추가된다면 어떻게 개선하면 좋을까요?

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/navigation/BottomNavItem.kt
> +    )
[3]
AuthNavItem은 object, 여기는 data object로 선언을 했는데 둘의 차이점은 무엇일까요! 이렇게 선언해준 이유가 있을까요?

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/MainActivity.kt
> +        }
[2]
모든 화면이 signUpViewModel을 공유하고 있네요! 각 화면 별로 필요한 데이터가 다를텐데 하나의 뷰모델을 공유하기엔 추후 유지보수가 힘들어질 수 있을 것 같습니다! 어떻게 하면 좋을까요??

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +                        )
[1]
텍스트필드의 onValueChange에서 이미 값을 변경해주고 있는데 클릭 시에 불필요한 이중변경이 들어간게 맞는거 같습니다! 이 부분은 삭제하도록 하고 뷰모델에서 관리하는 아이디와 비밀번호를 어떻게 가져다 쓰고 가공하면 좋을 지 찾아볼까요? 
(hint : 백킹 프로퍼티, private fun 함수)

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +                        ) {
[1]
저도 그렇게 생각합니다! 아이디와 비밀번호를 스크린, 뷰모델 어디서 관리하는게 좋을 지 고민해보고 그에 따라 어떻게 효과적으로 호출하면 좋을지 고민해봅시다! MVVM의 탄생 배경과 활용법에 대해서 더 알아보면 좋을 것 같아요!

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +                            }
[3]
이 부분은 어떤 역할일까요?

2024-10-27 14:40 UTC, SYAAINN commented on app/src/main/java/org/sopt/and/presentation/viewmodel/SignInViewModel.kt
> +
[3]
자기 자신을 파라미터로 받고있는 이유가 있을까요??

2024-10-28 01:50 UTC, jangsjw approved these changes

2024-10-30 05:23 UTC, SYAAINN approved these changes

2024-10-30 05:50 UTC, hwidung commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +                        ) {
view model 관련해서 리뷰 달아주신 덕분에 더 알아보고 공부할 수 있었습니당 감사합니다 👍👍

2024-10-30 05:51 UTC, hwidung commented on app/src/main/java/org/sopt/and/presentation/viewmodel/SignInViewModel.kt
> +
사실,,, 이건 SignInViewModel, SignUpViewModel 다른 클래스라 자신을 파라미터로 받는게 아니긴 한데 ... 🥺 이름을 너무 헷갈리게 지은 탓일까요 ... SignUp에서 썼던 이메일,패스워드랑 SignIn에서 쓸 이메일, 패스워드를 비교하려고 이렇게 파라미터로 받았습니다!

2024-10-30 06:03 UTC, hwidung commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +                            }
launchSingleTop = true 부분은 스택에 같은 화면이 여러 개 쌓이는 것을 방지하는 옵션입니다! 예를 들면, 이미 Main이 최상단에 있는 상태에서 다시 Main 화면으로 네비게이션 하려고 할 때 새 인스턴스를 쌓지 않고 기존 화면을 그대로 사용하는 옵션입니다 !! 네비게이션 동작에 있어서 여러 옵션을 사용해 보려고 써봤어용 ㅎ...

2024-10-30 23:28 UTC, jihyunniiii reviewed
고생하셨습니다!!

2024-10-30 23:28 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +fun SignInScreen(signUpViewModel: SignUpViewModel, navController: NavHostController) {
하위 Composable 함수에서 NavHostController를 인자로 받는 것은 권장되지 않는 방법있니다.
NavHostController 대신 Screen 함수에서 이를 사용하는 부분을 함수화해서 인자로 넘겨주는 방법을 공부해보시면 좋을 것 같아요!

2024-10-30 23:28 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignInScreen.kt
> +    var isPasswordVisible by remember { mutableStateOf(false) }
이런 변수들은 viewModel에서 관리해도 좋겠네요.
세미나 때 MVVM 구조를 사용하는 것이 UI 로직과 비즈니스 로직을 분리하여 유지보수성을 높이기 위해서라고 말했죠?
어떤 것이 UI로직이고 어떤것이 비즈니스 로직인지 고민해보는 시간을 가지는 것도 좋을 것 같네요.

2024-10-30 23:28 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/ui/auth/SignUpScreen.kt
> +fun SignUpScreen(signUpViewModel: SignUpViewModel, navController: NavHostController) {
지금 다른 분들 코드를 보면 Route 함수와 Screen 함수를 분리해서 작성한 분들이 많을텐데요
이러한 형식을 가지는 것이 어떤 이점이 있는지 찾아보셔도 좋을 것 같습니다.

2024-10-30 23:28 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/ui/auth/component/CustomTextField.kt
> +            trailingIcon?.invoke()
invoke 함수가 무슨 역할을 하는지 추가적으로 공부해보시는 거 추천드립니다.

2024-10-30 23:28 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/ui/main/HomeScreen.kt
> +}
이런 값들은 전역으로 선언하는 것보다 뷰모델을 이용해 선언하는 것이 좋아보여요.
전역적으로 사용할 값이 아니라 이 뷰에서 사용하는 값이니까요.

2024-10-30 23:28 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/ui/main/HomeScreen.kt
> +        items(moviePosters.size) { index ->
세미나 때 key 값에 대해서 이야기 했었죠?
다시 공부하고 적용시켜보는 거 추천드립니다.

2024-10-30 23:28 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/presentation/viewmodel/SignInViewModel.kt
> +
이런 구조는 viewModel 간 의존성이 강해지게 되죠? (하나의 뷰모델을 만들 때 다른 뷰모델도 만들어야 하니까요.)
그렇기 때문에 별로 권장하지 않는 구조입니다.
유지 보수성 등을 이유로 MVVM 을 사용하는 것인데 이러면 유지보수성이 더 어려워지는 거니까요.
그리고 일반적으로 각 viewModel은 해당 화면의 로직만을 담당하도록 작성하는 것이 좋기에 (단일 책임 원칙) 어떤 식으로 하면 이러한 구조를 사용하지 않아도 되는지 고민해보시는 것 추천 드립니다.

2024-11-01 06:19 UTC, merged